update

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -27,8 +27,8 @@ jobs:
           echo "::endgroup::"
           FAIL=${{ steps.one.outcome == 'failure' || steps.two.outcome == 'failure' || steps.three.outcome == 'failure' }}
           echo $FAIL
-          if [ "$FAIL" != "" ]; then echo "failed"; fi
-          if [ "$FAIL" != "" ]; then echo "::error::One or more steps failed"; exit 1; fi
+          if [ "$FAIL" == "" ]; then echo "failed"; fi
+          if [ "$FAIL" == "" ]; then echo "::error::One or more steps failed"; exit 1; fi
 
     - id: one
       continue-on-error: true
