update

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -26,12 +26,12 @@ jobs:
           echo "three=${{ steps.three.outcome }}"
           echo "::endgroup::"
           FAIL=${{ steps.one.outcome == 'failure' || steps.two.outcome == 'failure' || steps.three.outcome == 'failure' }}
-          echo $FAIL
-          if [ "$FAIL" == "" ]; then echo "failed"; fi
-          if [ "$FAIL" == "" ]; then echo "::error::One or more steps failed"; exit 1; fi
+          echo "$FAIL"
+          if [ "$FAIL" != "" ]; then echo "failed"; fi
+          if [ "$FAIL" != "" ]; then echo "::error::One or more steps failed"; exit 1; fi
 
     - id: one
-      if: ${{ 1 == 2 }}
+      #if: ${{ 1 == 2 }}
       continue-on-error: true
       run: exit 1
     - id: two
